env:
  CIRRUS_CLONE_DEPTH: 1
container:
  image: apon77/aosp:latest
  cpu: 10
  memory: 24G

task:
    name: Rom Builder
    timeout_in: 120m
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_script:
      - ./upload
