#!/bin/bash
cd /tmp

# Normal build steps
source build/envsetup.sh
lunch aosp_sakura-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
mka bacon -j$(nproc --all)

ccache -s