#!/bin/bash

cd /tmp
export CCACHE_DIR=/tmp/ccache

while true
do
ccache -s
tar --use-compress-program="pigz -k -1 " -cf romccache.tar.gz ccache
rclone copy romccache.tar.gz gdrive: -P
rm -rf romccache.tar.gz
sleep 15m
done
