#!/bin/bash
cd /tmp

repo init --no-repo-verify --depth=1 -u https://github.com/PixelExperience/manifest -b eleven -g default,-device,-mips,-darwin,-notdefault

echo "${git_cookies}" > ~/setup_cookies.sh
bash ~/setup_cookies.sh

git clone https://"${git_auth}"@gitlab.com/Sakura-Development/device_xiaomi_sakura device/xiaomi/sakura --depth=1
git clone https://"${git_auth}"@gitlab.com/Sakura-Development/vendor_xiaomi_sakura vendor/xiaomi/sakura --depth=1
git clone https://github.com/PixelExperience-Devices/kernel_xiaomi_rosy kernel/xiaomi/sakura --depth=1 ### just for headers lol

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
